version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=packulator
      - DB_PASSWORD=packulator123
      - DB_NAME=packulator
      - DB_SSL_MODE=disable
      - ENVIRONMENT=production
      - LOG_LEVEL=debug
      - DEBUG=true
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=packulator
      - POSTGRES_PASSWORD=packulator123
      - POSTGRES_DB=packulator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U packulator -d packulator"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
