# Railway Nixpacks configuration - Backend only
[phases.setup]
nixPkgs = ["go_1_24"]

[phases.build]
cmds = [
    "go mod download",
    "CGO_ENABLED=0 go build -o main ./cmd/main.go"
]

[start]
cmd = "./main"